### ISSUE TITLE
JDBC null pointer exception

### ISSUE THREAD

**Issue by chathaway-codes** [YottaDB/PIP#77]
# Final Release Note

 

# Description

When attempting to use the JDBC driver to connect to a Docker container running the MTM, I got this error:
 
```
java.lang.NullPointerException
	at sanchez.jdbc.driver.ScDriver.connect(ScDriver.java:283)
	at net.sourceforge.squirrel_sql.fw.sql.SQLDriverManager.getConnection(SQLDriverManager.java:133)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:167)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.access$000(OpenConnectionCommand.java:45)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand$1.run(OpenConnectionCommand.java:104)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
I'm not sure what the cause is just yet; the line in question looks harmless enough.

# Draft Release Note

**Comment by ChristopherEdwards** [comment]
Any notes on replicating this? I just fired up a docker container using the image at yottadb/octo:latest with SquirrelSQL and this error message doesn't appear

**Comment by chathaway-codes** [comment]
It appears to be related to the port the JDBC driver is connecting to not being available or listened on; I'm not sure why the Docker container wasn't listening.
Any case, it should error more gracefully when this happens.

**Comment by ChristopherEdwards** [comment]
I've updated the docker run command on the docker hub issue which corrects the documentation part of the error.

Agreed that a NPE shouldn't happen and a more user-friendly error message should be given.
